[package]
name = "logic-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "logic_parser"
crate-type = ["lib"]

[features]
default = []
image-generation = ["dep:imageproc", "dep:image"]

[dependencies]
image = { version = "0.24.7", optional = true }
imageproc = { version = "0.23.0", optional = true }
thiserror = "1.0.47"

[dev-dependencies]
assert_json = "0.1.0"
