[package]
name = "logic-parsers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic-parser = { path = "../logic-parser" }
wasm-bindgen = "0.2.87"
console_error_panic_hook = "0.1.7"
